test

diff --git a/.github/workflows/Build SukiSU Ultra OnePlus.yml b/.github/workflows/Build SukiSU Ultra OnePlus.yml
--- a/.github/workflows/Build SukiSU Ultra OnePlus.yml
+++ b/.github/workflows/Build SukiSU Ultra OnePlus.yml
@@ -60,14 +60,37 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Maximize Build Space
-        uses: easimon/maximize-build-space@master
-        with:
-          root-reserve-mb: 8192
-          temp-reserve-mb: 2048
-          remove-dotnet: 'true'
-          remove-android: 'true'
-          remove-haskell: 'true'
-          remove-codeql: 'true'
+        run: |
+          export DEBIAN_FRONTEND=noninteractive
+          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
+          
+          df -h
+          
+          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /opt/hostedtoolcache/CodeQL /usr/local/share/powershell /usr/share/swift || true
+          sudo docker image prune --all --force
+          echo "some directories deleted"
+          
+          # Remove large unwanted packages
+          sudo apt-get purge -y \
+            aria2 ansible azure-cli shellcheck rpm xorriso zsync \
+            esl-erlang firefox gfortran-8 gfortran-9 google-chrome-stable \
+            google-cloud-sdk imagemagick \
+            libmagickcore-dev libmagickwand-dev libmagic-dev ant ant-optional kubectl \
+            mercurial apt-transport-https mono-complete libmysqlclient \
+            unixodbc-dev yarn chrpath libssl-dev libxft-dev \
+            libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev \
+            snmp pollinate libpq-dev postgresql-client powershell ruby-full \
+            sphinxsearch subversion mongodb-org microsoft-edge-stable || true
+          
+          # Regex-based purges (for bulk families like mysql, php, dotnet)
+          sudo apt-get purge -y $(dpkg-query -W -f='${binary:Package}\n' | grep -E '^mysql|^php|^dotnet') || true
+          
+          # Clean up
+          sudo apt-get autoremove -y
+          sudo apt-get autoclean -y
+          echo "some packages purged"
+          
+          df -h
 
       - name: Extract OnePlus Manifest Info
         id: extract_info
@@ -581,13 +604,9 @@ jobs:
           sed -i "s/KBUILD_CFLAGS += -mcpu=oryon-1//" ./common/Makefile
           sed -i 's/check_defconfig//' ./common/build.config.gki
           sed -i 's/r510928/r536225/' ./common/build.config.constants
-          #rm -rf ./common/check_file.sh
-          #sed -i '/obj-\$(CONFIG_IS_STARKERNELL)[[:space:]]*+=[[：space:]]*starkernel/d' ./common/drivers/Makefile
-          #sed -i '/[[:space:]]*source[[:space:]]\+"drivers\/starkernel\/Kconfig"[[:space:]]*/d' ./common/drivers/Kconfig
-          cd ./common
-          git revert 0dbc805bbbaa8bf36c1531560ba7abb4e4f2088c
-          git add -A
-          git commit -m "removed"
+          rm -rf ./common/check_file.sh
+          sed -i '/obj-\$(CONFIG_IS_STARKERNELL)[[:space:]]*+=[[：space:]]*starkernel/d' ./common/drivers/Makefile
+          sed -i '/[[:space:]]*source[[:space:]]\+"drivers\/starkernel\/Kconfig"[[:space:]]*/d' ./common/drivers/Kconfig
       # Custom kernel build time, without adding #1 SMP PREEMPT 自定义内核构建时间，不要加入#1 SMP PREEMPT
       - name: Custom BUILD_TIME
         shell: bash
